In [14]:
import numpy as np

#Numpy usado para fórmulas e cálculos matemáticos com matrizes.

def linha():
    print('-----------')
    

In [5]:
#Criar matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])
print(mt)
print(type(mt))


[12 34 26 18 10]
<class 'numpy.ndarray'>


In [6]:
#Criar array com um tipo especifico
#criar array como float de 64bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat) 
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
#Mudar tipo do array
#Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999])
print(mtnew)
#Quando mudamos de float para Int os valores são truncados
mtnewint = mtnew.astype(np.int32)
mtnewint #apenas o nome da variável faz imprimi-la 

[ 1.4     3.6    -5.1     9.42    4.9999]


array([ 1,  3, -5,  9,  4])

In [8]:
#também podemos fazer o inverso
mt5 = np.array([1, 2, 3, 4, 5])
print(mt5)
mt6 = mt5.astype(float)
mt6

[1 2 3 4 5]


array([1., 2., 3., 4., 5.])

In [10]:
#Criar uma matriz com mais de uma dimensão
#Matrix BiDimensional
mt7 = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
mt7

array([[ 7,  2, 23],
       [12, 27,  4],
       [ 5, 34, 23]])

In [11]:
#Criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios.
vazio = np.empty([3, 2], dtype = int)
print(vazio)
print('-----')
#cria uma matriz 4x3 com valores zero, o primeiro é linha o segundo é coluna
zeros = np.zeros([4, 3])
print(zeros)
print('-----')
#Cria com valores igual a um
um = np.ones([4, 3])
print(um)
print('-----')
#cria matriz diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)
print('-----')

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----


In [19]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
linha()
#valores aleatórios distribuição normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
linha()
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3, 4))) #o 10* significa que os valores aleatórios serão multiplicados por 10
print(ale3)
linha()

[0.7752248  0.46536219 0.75869261 0.54730256 0.02105937]
-----------
[ 1.1541329   0.23715719 -0.32187699  0.03906291  0.87270524]
-----------
[[5.83295965 0.52044137 7.32127818 6.5711594 ]
 [6.65790151 8.44191504 1.65943085 9.42590324]
 [1.58805145 3.44043604 7.97354032 8.27177751]]
-----------


In [20]:
#Outras formas de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1) #O uso de semente significa que estes números aleatórios serão sempre repetidos pois eles foram atribuídos a semente 1.
ale5 = gnr.random(3)
print(ale5)
linha()
#gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)
linha()

[0.51182162 0.9504637  0.14415961]
-----------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]
-----------


In [22]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
j

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
#funções especificas
#criar matriz bidimensional k
k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
print(k)
print(k[0][1]) #mostra elementos específicos da matriz
print(k.shape) #mostra formato da matriz

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [24]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [25]:
#funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [26]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [27]:
#extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [30]:
#adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print("-------")
res2 = n*o
print(res2)
print("-------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [31]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14 
# em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [32]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
# rearranja um conjunto de 15 elementos 
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [33]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1) #where parecido com if, if x > 0, 1 else -1
print(z)

[[ 1.08726751 -0.76318607 -0.22957317 -1.24899104]
 [ 0.91547188  0.29499071 -1.52418489 -0.39285446]
 [ 1.62730257 -0.30184228 -0.38605342 -0.4650876 ]
 [-2.28370067 -1.35281685 -0.53621538 -1.09951293]]
[[ True False False False]
 [ True  True False False]
 [ True False False False]
 [False False False False]]
[[ 1 -1 -1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1 -1]
 [-1 -1 -1 -1]]
